#!/bin/bash
set -e

if [ "$1" = "purge" ]; then
    # Remove configuration
    [ -d "/etc/jasmin" ] && rm -fr /etc/jasmin
    # Remove logs
    [ -d "/var/log/jasmin" ] && rm -fr /var/log/jasmin
fi

if [ "$1" = "remove" ]; then
    # remove jasmind start script
    systemctl stop jasmind
    systemctl disable jasmind
fi

if [ "$1" = "remove" ]; then
    # remove interceptord start script
    systemctl stop jasmin-interceptord
    systemctl disable jasmin-interceptord
    # remove dlrd start script
    systemctl stop jasmin-dlrd
    systemctl disable jasmin-dlrd
    # remove dlrlookupd start script
    systemctl stop jasmin-dlrlookupd
    systemctl disable jasmin-dlrlookupd
    # remove restapi start script
    systemctl stop jasmin-restapi
    systemctl disable jasmin-restapi
    # remove celery start script
    systemctl stop jasmin-celery
    systemctl disable jasmin-celery
fi

exit 0
