#!/bin/bash
set -e

# Add user & group
addgroup --system jasmin
adduser --disabled-login \
		--disabled-password \
		--system \
		--home /usr/lib/jasmin \
		--ingroup jasmin \
		--no-create-home \
		--gecos "Jasmin SMS Gateway" \
		jasmin

# Create required folders
[ -d "/var/log/jasmin" ] || mkdir /var/log/jasmin

# Change owner of required folders
chown jasmin. /etc/jasmin/store/
chown jasmin. /var/log/jasmin

# Install init script
if [ -x "/lib/systemd/system/jasmind.service" ]; then
	systemctl enable jasmind
	systemctl start jasmind || exit $?
fi

# Install init script
if [ -x "/lib/systemd/system/interceptord.service" ]; then
	systemctl enable interceptord
	systemctl start interceptord || exit $?
fi

exit 0
