#!/bin/bash
set -e

if [ "$1" = "purge" ]; then
    # Remove configuration
    [ -d "/etc/jasmin" ] && rm -fr /etc/jasmin
    # Remove logs
    [ -d "/var/log/jasmin" ] && rm -fr /var/log/jasmin
fi

if [ "$1" = "remove" ]; then
    # remove jasmind start script
    systemctl stop jasmind
    systemctl disable jasmind
fi

if [ "$1" = "remove" ]; then
    # remove interceptord start script
    systemctl stop interceptord
    systemctl disable interceptord
fi

exit 0
