#!/bin/bash
set -e

# stop jasmin server
if [ -f /lib/systemd/system/jasmind.service ]; then
  systemctl stop jasmind
fi

# stop interceptor server
if [ -f /lib/systemd/system/jasmin-interceptord.service ]; then
  systemctl stop jasmin-interceptord
fi

# stop dlrd server
if [ -f /lib/systemd/system/jasmin-dlrd.service ]; then
  systemctl stop jasmin-dlrd
fi

# stop dlrlookupd server
if [ -f /lib/systemd/system/jasmin-dlrlookupd.service ]; then
  systemctl stop jasmin-dlrlookupd
fi
