#!/bin/bash
set -e

# stop jasmin server
if [ -f /lib/systemd/system/jasmind.service ]; then
  systemctl stop jasmind &> /dev/null
fi

# stop interceptor server
if [ -f /lib/systemd/system/interceptord.service ]; then
  systemctl stop interceptord &> /dev/null
fi
