#!/bin/sh
set -e

# stop jasmind server
if [ -x "/etc/init.d/jasmind" ]; then
	invoke-rc.d jasmind stop || exit $?
fi

# stop interceptord server
if [ -x "/etc/init.d/interceptord" ]; then
	invoke-rc.d interceptord stop || exit $?
fi
