#!/bin/sh
set -e

# stop jasmind server
if [ -f /lib/systemd/system/jasmind.service ]; then
  systemctl stop jasmind &> /dev/null
fi

# stop interceptord server
if [ -f /lib/systemd/system/interceptord.service ]; then
  systemctl stop interceptord &> /dev/null
fi
