#!/bin/sh
set -e

# stop jasmind server
if [ -f /lib/systemd/system/jasmind.service ]; then
  systemctl stop jasmind
fi

# stop interceptor server
if [ -f /lib/systemd/system/jasmin-interceptord.service ]; then
  systemctl stop jasmin-interceptord
fi

# stop dlrd server
if [ -f /lib/systemd/system/jasmin-dlrd.service ]; then
  systemctl stop jasmin-dlrd
fi

# stop dlrlookupd server
if [ -f /lib/systemd/system/jasmin-dlrlookupd.service ]; then
  systemctl stop jasmin-dlrlookupd
fi

# stop restapi server
if [ -f /lib/systemd/system/jasmin-restapi.service ]; then
  systemctl stop jasmin-restapi
fi

# stop celery server
if [ -f /lib/systemd/system/jasmin-celery.service ]; then
  systemctl stop jasmin-celery
fi
